---
layout: page
title: "Logistic Regression"
subtitle: R Handout
author: "Derek H. Ogle"
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3
    fig_width: 3
    self_contained: no
  pdf_document:
    fig_width: 3
    fig_height: 3
---

```{r echo=FALSE, eval=FALSE}
#=============================================================
#=============== IGNORE/DELETE FROM HERE .... ================
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCMTH207/modules/LogisticRegression")
source("../../rhelpers/rhelpers.R")
modHTML("RHO")
```

```{r echo=FALSE, results='hide', message='FALSE'}
source("../../rhelpers/knitr_setup.R")
#=============== .... TO HERE ================================
#=============================================================
```
----

## Initialization

```{r results='hide', message=FALSE, warning=FALSE}
library(NCStats)
```

----

# Bat Morphology Example
## Background


```{r}
setwd("C:/aaaWork/Web/GitHub/NCMTH207/modules/LogisticRegression")
```


```{r echo=FALSE, results="hide", message=FALSE, warnings=FALSE}
purl2("RHO.Rmd")
```
