# the following plots are used for the lecture slides
library(FSA)
bat <- lencat(~canine10,data=bat,startcat=2.6,w=0.1)
tbl <- with(bat,table(LCat,subsp))
ptbl <- prop.table(tbl,margin=1)
prsem <- ptbl[,2]
prsem[1:4] <- c(0.999,0.99,0.98,0.96)
prsem[10:12] <- c(0.02,0.01,0.001)
xs <- as.numeric(names(prsem))
windows(4.5,4.5); par(mar=c(3.5,3.5,1,1),mgp=c(2,0.75,0))
plot(prsem~xs,pch=3,col="blue",cex=1.25,xlab=xlbl,ylab="Proportion Semotus")
oddssem <- prsem/(1-prsem)
plot(oddssem~xs,pch=3,col="blue",cex=1.25,xlab=xlbl,ylab="Odds Semotus")
logitsem <- log(oddssem)
plot(logitsem~xs,pch=3,col="blue",cex=1.25,xlab=xlbl,ylab="Logit(Probability Semotus)")
