---
title: "IVR Lecture"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3.5
    fig_width: 3.5
    self_contained: false
---

```{r echo=FALSE, eval=FALSE, warning=FALSE}
## Renders an appropriate HTML file and moves to CE directory
source("rhelpers/rhelpers.R")
modHTML("modules/IVRegression/Lecture_IVR_NRGDensity")
```
```{r echo=FALSE, include=FALSE, message=FALSE, warning=FALSE}
library(NCStats)
knitr::opts_chunk$set(prompt=TRUE,comment="")
```

----

## Background
[Hartman and Brandt (1995)](https://www.researchgate.net/profile/Kyle_Hartman/publication/250019672_Estimating_Energy_Density_of_Fish/links/0a85e52e51c7c8df25000000.pdf) examined the relationship between energy density (J/g wet weight) and percent dry weight for four species -- Bay Anchovy (*Anchoa mitchilli*), Bluefish (*Pomatomus saltatrix*), Striped Bass (*Morone saxatilis*), and Weakfish (*Cynoscion regalis*). Their primary interest was to determine how energy density was related to percent dry weight and if the relationship differed among species. The recorded energy density values were converted from J/g to kJ/g to better represent significant digits.

```{r}
options(show.signif.stars=FALSE)
library(NCStats)
FED <- read.csv("https://raw.githubusercontent.com/droglenc/NCData/master/FishEnergyDensity.csv")
FED$ed2 <- FED$ed/1000
str(FED)
levels(FED$species)
```

This represents an indicator variable regression because the response variable (energy density) is quantitative and there is a quantitative explanatory variable (dry weight), which is called a covariate, and a categorical explanatory variable (species).

<div class="alert alert-info">
<ul>
  <li>The concept of an indicator variable was described in [this video](https://vimeo.com/398994393).</li>
</ul>
</div>

<br>

## Model Setups
Three indicator variables are required to represent the four species.

* BF=1 if Bluefish, =0 otherwise
* SB=1 if Striped Bass, =0 otherwise
* WF=1 if Weakfish, =0 otherwise

With this Bay Anchovy are the reference group. Constructing indicator variables was described in [this video](https://vimeo.com/399006140).

The ultimate full model is

* &mu;<sub>ED</sub> = &alpha; + &beta;DW + &delta;<sub>1</sub>BF + &delta;<sub>2</sub>SB + &delta;<sub>3</sub>WF + &gamma;<sub>1</sub>BF&times;DW + &gamma;<sub>2</sub>SB&times;DW + &gamma;<sub>3</sub>WF&times;DW,

where ED is energy density and DW is dry weight. The corresponding submodels are

* Bay Anchovy: &mu;<sub>ED</sub> = &alpha; + &beta;DW
* Bluefish: &mu;<sub>ED</sub> = (&alpha;+&delta;<sub>1</sub>) + (&beta;+&gamma;<sub>1</sub>)DW
* Striped Bass: &mu;<sub>ED</sub> = (&alpha;+&delta;<sub>2</sub>) + (&beta;+&gamma;<sub>2</sub>)DW
* Weakfish: &mu;<sub>ED</sub> = (&alpha;+&delta;<sub>3</sub>) + (&beta;+&gamma;<sub>3</sub>)DW

The ultimate full model is fit in R with
```{r}
lm1 <- lm(ed2~dw*species,data=FED)
```

A quick check of assumptions suggests that they are all met.
```{r eval=FALSE}
transChooser(lm1)
```
```{r echo=FALSE, fig.width=7, fig.height=3.5, par1=TRUE}
NCStats:::iAssumPlot_REGRESS(NCStats:::iTypeoflm(lm1),
                             lambday=1,shifty=0,lambdax=1,shiftx=0,
                             show.stats=TRUE,alpha=0.05,col.hist="gray70")
```

The model parameters have the following meanings:

* &alpha; is the intercept for Bay Anchovy (reference group).
* &beta; is the slope for Bay Anchovy (reference group).
* &delta;<sub>1</sub> is the difference in intercept of Bluefish and Bay Anchovy
* &delta;<sub>2</sub> is the difference in intercept of Striped Bass and Bay Anchovy
* &delta;<sub>3</sub> is the difference in intercept of Weakfish and Bay Anchovy
* &gamma;<sub>1</sub> is the difference in slopes of Bluefish and Bay Anchovy
* &gamma;<sub>2</sub> is the difference in slopes of Striped Bass and Bay Anchovy
* &gamma;<sub>3</sub> is the difference in slopes of Weakfish and Bay Anchovy

Estimates (and 95% CIs) of the model parameters are obtained with
```{r}
cbind(Ests=coef(lm1),confint(lm1))
```

<div class="alert alert-info">
<ul>
  <li>Constructing the ultimate full model and submodels, descriptions of the meanings of the parameters, and the R code were described in [this video](https://vimeo.com/398994239).</li>
</ul>
</div>

<br>

## Parallel Lines Test
The hypothese (and, thus, models) for the parallel lines test are as follows:

* H<sub>0</sub>: &mu;<sub>ED</sub> = &alpha; + &beta;DW + &delta;<sub>1</sub>BF + &delta;<sub>2</sub>SB + &delta;<sub>3</sub>WF
* H<sub>A</sub>: &mu;<sub>ED</sub> = &alpha; + &beta;DW + &delta;<sub>1</sub>BF + &delta;<sub>2</sub>SB + &delta;<sub>3</sub>WF + &gamma;<sub>1</sub>BF&times;DW + &gamma;<sub>2</sub>SB&times;DW + &gamma;<sub>3</sub>WF&times;DW

The ANOVA table for conducting the parallel lines test is below
```{r}
anova(lm1)
```

The p-value for the interaction term (`r kPvalue(anova(lm1)[3,5],latex=FALSE)`; i.e., last p-value in table above) is clearly less than &alpha; indicating that H<sub>0</sub> should be rejected. This results indicates that the slopes for the regressions between energy density and dry weight differ among species and, thus, the relationship between energy density and dry weight differs among the species.

<div class="alert alert-info">
<ul>
  <li>Parallel lines tests were described in [this video](https://vimeo.com/398994330).</li>
</ul>
</div>

<div class="alert alert-warning">
<ul>
  <li>To this point was largely review from previous materials</li>
</ul>
</div>


The parallel lines test indicates SOME difference in slopes between the species, but not specifically which species' slopes are different. The following video explains what we should do to identify the specific differences.

<iframe src="https://player.vimeo.com/video/399210843" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>

The results of `compSlopes()` below were shown in the video.
```{r}
compSlopes(lm1)
```

As discussed in the video, these results show that the slope for Bay Anchovy differs from the slopes for the other three species (top three p-values) but that the slopes for the other three species are not different (bottom three p-values). The first three `diff`erences in the top portion of the results suggest that the slope for Bay Anchovy is less than the slopes for the other three species. The slopes and confidence intervals in the bottom portion of the reslts also suggest that the slope for Bay Anchovy is less than the slope for the other three species.

These results are illustrated in the following fitted-line plot.
```{r echo=-1}
par(mar=c(3,3,0.5,0.5),mgp=c(1.9,0.5,0),tcl=-0.2)
fitPlot(lm1,xlab="% Dry Weight",ylab="Energy Density (kJ/g)",
        legend="topleft",cex.leg=0.8)
```


<br>

## Equal Intercepts (Coincident Lines) Test
For the three species above that had the same slope it is useful to also determine if they have the same intercepts or not. If they have the same intercepts (and the same slopes) then they can be modeled with the same line.

To begin this analysis I reduced the data frame to just these three species (by eliminating Bay Anchovy), fit the ultimate full model to just these species, reaffirm that they have the same slopes (i.e., examine the parallel lines test for just these three species), and determine if they have the same intercept or not.

```{r}
FED1 <- filterD(FED,species!="bayanchovy")
lm2 <- lm(ed2~dw*species,data=FED1)
anova(lm2)
```

The interaction (bottom) p-value does reaffirm that these three species have the same slope (and are, thus, parallel). Given that the lines are parallel it is possible then to perform the equal intercepts test. The hypotheses for equal intercepts test are

* H<sub>0</sub>: &mu;<sub>ED</sub> = &alpha; + &beta;DW
* H<sub>A</sub>: &mu;<sub>ED</sub> = &alpha; + &beta;DW + &delta;<sub>1</sub>SB + &delta;<sub>2</sub>WF

<div class="alert alert-info">
<ul>
  <li>Equal intercepts tests were described in [this video](https://vimeo.com/398994330).</li>
</ul>
</div>

The p-value for the factor variable (`r kPvalue(anova(lm2)[2,5],latex=FALSE)`; i.e., the second line) is less than &alpha; and the H<sub>0</sub> for the equal intercepts test is rejected. Thus, there is a difference in intercepts among these three species. The following video explains what we should do to indentify which pairs of intercepts are different.

<iframe src="https://player.vimeo.com/video/399283122" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>

The results of `compIntercepts()` below were shown in the video.

```{r}
compIntercepts(lm2,common.cov=0)
```

The top of this output shows that the intercept for Bluefish differs from the intercepts for the other two species (top two p-values), which do not differ (bottom p-value). The bottom of this output shows the estimated intercepts for the three species. This bottom output is not particularly interesting because it shows the mean energy density when the percent dry weight is 0 (which is where the `common.cov=0` argument came into play), which is not useful.

If the `common.cov=0` argument is ignored then `compIntercepts()` will show the mean energy density at the mean percent dry weight, which is more useful. Given that the lines are parallel difference at any value of X will be the same as when X=0. Thus, the top portion of the output did not change.
```{r}
compIntercepts(lm2)
```

These results are visualized with the following fitted line plot.
```{r echo=-1}
par(mar=c(3,3,0.5,0.5),mgp=c(1.9,0.5,0),tcl=-0.2)
fitPlot(lm2,xlab="Dry Weight",ylab="Energy Density (kJ/g)",
        legend="topleft",cex.leg=0.8)
```


----
