---
title: "Exercise Key"
subtitle: "Two-Way ANOVA"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3.5
    fig_width: 3.5
    self_contained: false
---

```{r echo=FALSE, eval=FALSE, warning=FALSE}
## Renders an appropriate HTML file and moves to CE directory
source("modules/aaa_ExcKeys/aaa_rmd/zzz_modHTML_CEKeys.R")
modHTML_CEKeys("KEY_Anova-2way_Crayfish")
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
library(dplyr)
library(huxtable)
library(captioner)
tbls <- captioner(prefix="Table")
figs <- captioner(prefix="Figure")
tbls(name="aov","Analysis of variance table for inverse transformed crayfish activity level by feeding regime and temperature.")
tbls(name="mcpci1","Tukey's multiple comparison confidence intervals for the feeding regime in the two-way ANOVA of inverse transformed crayfish activity level by feeding regime and temperature.")
tbls(name="mcp2","Tukey's multiple comparison results for the time of day term in the two-way ANOVA of inverse transformed crayfish activity level by feeding regime and temperature.")
tbls(name="mcpci2","Tukey's multiple comparison confidence intervals for the time of day term in the two-way ANOVA of inverse transformed crayfish activity level by feeding regime and temperature.")
figs(name="residplot1","Histogram of residuals (left) and boxplot of residuals by treatment group (right) for the crayfish and bass feeding study.")
figs(name="residplot2","Histogram of residuals (left) and boxplot of residuals by treatment group (right) for the inverse number of crayfish feeding in the crayfish and bass feeding study.")
figs(name="fitplot","Main effects plots for the two-way ANOVA of the inverse of activity level by feeding regime and temperature. Treatment means with different letters are significantly different.")
```

----

## Feeding Under Risk of Predation

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
  <li>These data were analyzed with an inverse transformation, which means that "small" values on the transformed scale are actually "large" values on the original scale. Thus, small means on the transformed scale actually represent more active crayfish on the original scale.</li>
  <li>No multiple comparisons p-values are shown for feeding regime because there are only two levels and it is already known from the ANOVA table that those two levels differ.</li>
</ul>
</div>

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(NCStats)
library(multcomp)

# Calculations
active <- c(3,2,3,2,2,2,7,14,4,4,10,5,4,2,4,3,2,4,4,3,4,3,4,4,
            24,33,41,6,22,28,12,35,31,30,24,39,3,3,4,2,5,3,49,
            13,40,48,47,47)
feed <- factor(c(rep("Fed",6),rep("Unfed",6),rep("Fed",12),
                 rep("Unfed",12),rep("Fed",6),rep("Unfed",6)))
time <- factor(c(rep(12,12),rep(17,24),rep(19,12)))
cray <- data.frame(active,feed,time)
lm1 <- lm(active~feed*time,data=cray)
lev1 <- levenesTest(lm1)
ad1 <- adTest(lm1$residuals)
out1 <- outlierTest(lm1)
cray$t.active <- cray$active^(-1)
lm2 <- lm(t.active~feed*time,data=cray)
lev2 <- levenesTest(lm2)
ad2 <- adTest(lm2$residuals)
out2 <- outlierTest(lm2)
aov2 <- anova(lm2)

mc2 <- glht(lm2,mcp(time="Tukey"))
mc3 <- glht(lm2,mcp(feed="Tukey"))
mc2p <- kGLHT(mc2)
mc2c <- kGLHT(mc2,type="confidence")
mc3c <- kGLHT(mc3,type="confidence")

```

1. The individuals (group of 50 crayfish) appear to be independent both within and among treatments. Independence within treatments is apparent as it was implied that different groups were used for each replicate and these groups were randomly selected. In other words there is no connection (like using the same group) among groups within treatments. Independence among treatments is indicated by the same reasoning. However, it is also evident that there is no connection (or pairing) of groups among treatments as the treatments have different numbers of replicates.
    On the original scale the variances are unequal (Levene's `r kPvalue(lev1[1,"Pr(>F)"],digits=4,latex=FALSE)`), the residuals are not normal (Anderson-Darling `r kPvalue(ad2$p.value,digits=4,latex=FALSE)`) nor symmetric (`r figs("residplot1",display="cite")`), and there is one possible outlier (individual 44; `r kPvalue(out1$bonf.p,digits=4,latex=FALSE)`). The trial-and-error method suggested an inverse transformation for the number of active crayfish (response variable). This transformation provided equal variances (Levene's `r kPvalue(lev2[1,"Pr(>F)"],digits=4,latex=FALSE)`) and residuals that are not normal (Anderson-Darling `r kPvalue(ad2$p.value,digits=4,latex=FALSE)`) but, even though they were right-skewed, they were not "long-tailed" (`r figs("residplot2",display="cite")`). There are no significant outliers (`r kPvalue(out2$bonf.p,digits=4,latex=FALSE)`; `r figs("residplot2",display="cite")`)). Thus, the assumptions have been largely met on the inverse scale with no individuals removed.
1. There is no significant interaction effect (`r kPvalue(aov2[3,"Pr(>F)"],digits=4,latex=FALSE)`; `r tbls("aov",display="cite")`). There are significant main effects for both feeding regime (`r kPvalue(aov2[1,"Pr(>F)"],digits=4,latex=FALSE)`; `r tbls("aov",display="cite")`) and time of day (`r kPvalue(aov2[2,"Pr(>F)"],digits=4,latex=FALSE)`; `r tbls("aov",display="cite")`).
1. The mean inverse number of active crayfish was between `r formatC(-1*mc3c["upr"],format="f",digits=2)` and `r formatC(-1*mc3c["lwr"],format="f",digits=2)` lower for the fed than unfed crayfish (`r tbls("mcpci1",display="cite")`). Thus, significantly **more** crayfish were active in the FED then the UNFED treatments (`r figs("fitplot",display="cite")`).
  The mean inverse number of active crayfish was between `r formatC(-1*mc2c[1,"upr"],format="f",digits=2)` and `r formatC(-1*mc2c[1,"lwr"],format="f",digits=2)` lower at 1200 than at 1700 and between `r formatC(-1*mc2c[2,"upr"],format="f",digits=2)` and `r formatC(-1*mc2c[2,"lwr"],format="f",digits=2)` lower at 1200 than at 1900 (`r tbls("mcp2",display="cite")`; `r tbls("mcpci2",display="cite")`). The mean inverse number of active crayfish did not differ between 1700 and 1900 (`r tbls("mcp2",display="cite")`). Thus, there are significantly MORE crayfish active at 1700 and 1900 than at 1200, but there is no difference between 1700 and 1900.
1. Summary plots of these results are in `r figs("fitplot",display="cite")`.
1. These results show that there are more active crayfish in the unfed treatment and at 1700 and 1900 than at 1200. Thus, there are more active crayfish when competition is high and at dusk and early evening.

`r tbls("aov")`

```{r echo=FALSE, background="white"}
kANOVA(lm2)
```

&nbsp;

`r tbls("mcpci1")`

```{r echo=FALSE, background="white", comment=""}
mc2c
```

&nbsp;

`r tbls("mcp2")`

```{r echo=FALSE, background="white", comment=""}
mc2p
```

&nbsp;

`r tbls("mcpci2")`

```{r echo=FALSE, background="white", comment=""}
mc3c
```

&nbsp;


```{r echo=FALSE, fig.width=7, fig.height=3.5, par1=TRUE}
NCStats:::iAssumPlot_ANOVA(NCStats:::iTypeoflm(lm1),
                           lambda=1,shifty=0,show.stats=TRUE,boxplot=TRUE,
                           alpha=0.05,col.hist="gray70")
```

`r figs("residplot1")`

&nbsp;


```{r echo=FALSE, fig.width=7, fig.height=3.5, par1=TRUE}
NCStats:::iAssumPlot_ANOVA(NCStats:::iTypeoflm(lm1),
                           lambda=-1,shifty=0,show.stats=TRUE,boxplot=TRUE,
                           alpha=0.05,col.hist="gray70")
```

`r figs("residplot2")`

&nbsp;


```{r fitPlot, echo=FALSE, par1=TRUE}
fitPlot(lm2,which="feed",ylab="Inverse of Active Crayfish",
        xlab="Feeding Regime",ylim=c(0.05,0.42))
addSigLetters(lm2,which="feed",lets=c("z","y"),pos=c(2,4))
fitPlot(lm2,which="time",ylab="Inverse of Active Crayfish",
        xlab="Time of Day",ylim=c(0.05,0.42))
addSigLetters(lm2,which="time",lets=c("a","b","a"),pos=c(2,2,4))
```

`r figs("fitplot")`

R Appendix.
```{r eval=FALSE, prompt=FALSE}
setwd("c:/biometry/")
cray <- read.csv("CrayfishPredation.csv")
cray$time <- factor(cray$time)
lm1 <- lm(active~feed*time,data=cray)
transChooser(lm1)
cray$t.active <- cray$active^(-1)
lm2 <- lm(t.active~feed*time,data=cray)
transChooser(lm2)
anova(lm2)
mc2 <- glht(lm2,mcp(time="Tukey"))
summary(mc2)
<<fitPlot>>
```

----
