---
title: "Exercise Key"
subtitle: "Indicator Variable Regression"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3.5
    fig_width: 3.5
    self_contained: false
---

```{r echo=FALSE, eval=FALSE, warning=FALSE}
## Renders an appropriate HTML file and moves to CE directory
source("modules/aaa_ExcKeys/aaa_rmd/zzz_modHTML_CEKeys.R")
modHTML_CEKeys("KEY_IVR_Trawls2")
```
```{r echo=FALSE, include=FALSE, message=FALSE, warning=FALSE}
library(NCStats)
```

----

## Deep-Sea Trawling II

<ol start="1">
  <li>The indicator variables are defined below. Note that the "ANR" species will be the reference group</li>
  <ul>
    <li>"C" where C=1 if the species is "COA" and A=0 if the species is not "COA".</li>
    <li>"S" where S=1 if the species is "SYK" and S=0 if the species is not "SYK".</li>
  </ul>
</ol>

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
  <li>The indicator variables are named after the non-reference group. The reference group is alphabetically first in R. Thus, in this case the reference groups is "ANR" and the indicator variables are named after "COA" and "SYK."</li>
</ul>
</div>

<br>

<ol start="2">
  <li>The ultimate full model is &mu;<sub>LOG.MASS</sub> = &alpha; + &beta;DEPTH + &delta;<sub>1</sub>C + &delta;<sub>2</sub>S + &gamma;<sub>1</sub>C&times;DEPTH + &gamma;<sub>2</sub>S&times;DEPTH.</li>
</ol>

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
  <li>The variables are entered into the ultimate full model in this order -- covariate (i.e., depth), indicator variable (i.e., C and S), and the interaction variable.</li>
  <li>The covariate is always multiplied by &beta;, the indicator variables are always multiplied by &delta;s, and the interaction variables are always multiplied by &gamma;s.</li>
</ul>
</div>

<br>

<ol start="3">
  <li>The submodels for all groups are below</li>
  <ul>
    <li>ANR: &mu;<sub>LOG.MASS</sub> = &alpha; + &beta;DEPTH
    <li>COA: &mu;<sub>LOG.MASS</sub> = (&alpha;+&delta;<sub>1</sub>) + (&beta;+&gamma;<sub>1</sub>)DEPTH</li></li>
    <li>SYK: &mu;<sub>LOG.MASS</sub> = (&alpha;+&delta;<sub>2</sub>) + (&beta;+&gamma;<sub>2</sub>)DEPTH</li></li>
  </ul>
</ol>

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
  <li>The "ANR" submodel is found by plugging 0 in for C and S in the ultimate full model and then simplifying. Essentially everything in the ultimate full model multiplied by C or S is dropped.</li>
  <li>The "COA" submodel is found by plugging 1 in for C and 0 for S in the ultimate full model and then simplifying.</li>
  <li>The "SYK" submodel is found by plugging 0 in for C and 1 for S in the ultimate full model and then simplifying.</li>
</ul>
</div>

<br>

<ol start="4">
  <li>Interpretations of the coefficients are below.</li>
  <ul>
    <li>&alpha; is the intercept for ANR (reference group).</li>
    <li>&beta; is the slope for ANR (reference group).</li>
    <li>&delta;<sub>1</sub> is the difference in intercept of COA and ANR (i.e., COA-ANR)</li>
    <li>&delta;<sub>2</sub> is the difference in intercept of SYK and ANR (i.e., SYK-ANR)</li>
    <li>&gamma;<sub>1</sub> is the difference in slopes of COA and ANR (i.e., COA-ANR)</li>
    <li>&gamma;<sub>2</sub> is the difference in slopes of SYK and ANR (i.e., SYK-ANR)</li>
  </ul>
</ol>

<br>

<ol start="5">
  <li>The models for the "parallel lines test" are below.</li>
  <ul>
    <li>H<sub>0</sub>: &mu;<sub>LOG.MASS</sub> = &alpha; + &beta;DEPTH + &delta;<sub>1</sub>C + &delta;<sub>2</sub>S</li>
    <li>H<sub>A</sub>: &mu;<sub>LOG.MASS</sub> = &alpha; + &beta;DEPTH + &delta;<sub>1</sub>C + &delta;<sub>2</sub>S + &gamma;<sub>1</sub>C&times;TIME + &gamma;<sub>2</sub>S&times;TIME</li>
  </ul>
</ol>

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
  <li>The models in a "parallel lines" test differ only in whether the &gamma; parameters or the interaction variable exist as these are the parameters/variables that indicate if the slopes differ (non-parallel) or not (parallel). Thus, the H<sub>A</sub> is always the ultimate full model and the H<sub>0</sub> is always the ultimate full model without the interaction variables.</li>
</ul>
</div>

<br>

<ol start="6">
  <li>The models for the "intercepts test" (assuming parallel lines) are below.</li>
  <ul>
    <li>H<sub>0</sub>: &mu;<sub>LOG.MASS</sub> = &alpha; + &beta;DEPTH</li>
    <li>H<sub>A</sub>: &mu;<sub>LOG.MASS</sub> = &alpha; + &beta;DEPTH + &delta;<sub>1</sub>C + &delta;<sub>2</sub>S</li>
  </ul>
</ol>

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
  <li>The "equal intercepts" or "coincident lines" test is only tested assuming that the lines are parallel; thus, neither model will contain the &gamma; parameters or the interaction variables (as &gamma;<sub>1</sub>=0 and &gamma;<sub>2</sub>=0 for parallel lines). Thus, the models in the "coincident lines" test differ only in whether the models contain the &delta; parameters or the indicator variables.</li>
</ul>
</div>

----
