---
title: "Exercise Key Key"
subtitle: "Type of Analysis"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3.5
    fig_width: 3.5
    self_contained: false
---

```{r echo=FALSE, eval=FALSE, warning=FALSE}
## Renders an appropriate HTML file and moves to CE directory
source("modules/aaa_ExcKeys/aaa_rmd/zzz_modHTML_CEKeys.R")
modHTML_CEKeys("KEY_LMFoundations_TypeOfAnalysis")
```

----

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
<li>In the first question, a "menu item" is an individual, not a variable. Thus, it does not enter into the discussion about determining the type of analysis.</li>
<li>In all examples in this class there will only ever be one response variable. In these questions, this is most evident in the fourth question. First, "the relationship between" is a type of analysis, not a variable. Thus, one of "hip girth" and "body weight" is the response variable (think y-axis) and the other is the explanatory variable (think x-axis). As these are both quantitative, this is some sort of regression. The relationship (i.e., regression) between these two is going to be compared between two groups; thus, "sex" is another explanatory variable.</li>
<li>In question 5, the "number of snails" is categorical because groups were created 1, 2-5, or more than 5 individuals. The actual number of snails was not recorded.</li>
</ul>
</div>

----

<ol>
  <li>This is a <b><i>simple linear regression</b></i> because both variables are quantitative (it is not clear which one is the response variable; though, it is likely number of calories).</li>
  <li>This is a <b><i>1-way ANOVA</b></i> because the response variable (batting average) is quantitative and the explanatory variable (position) is categorical.  Additionally, the means are being compared among diffferent groups described by one factor variable.</li>
  <li>This is a <b><i>logistic regression</b></i> because the response variable (pass (or not) on the first attempt) is categorical (binomial) and the explanatory variable (grade-point-average) is quantitative.</li>
  <li>This is a <b><i>indicator variable regression</b></i> because the response variable (hip girth) is quantitative and one explanatory variable (body weight) is quantitative while the other explanatory variable (sex) is categorical.  Additionally, the research is attempting to determine if a relationship between two quantitative variables differs between two groups.</li>
  <li>This is a <b><i>2-way ANOVA</b></i> because the resonse variable (body temperature) is quantitative and the two explanatory variables (rock color and group size) are categorical.</li>
  <li>This is a <b><i>1-way ANOVA</b></i> because the response variable (chick weight) is quantitative and the explanatory variable (feed supplement type) is categorical.  Additionally, the means are being compared among diffferent groups described by one factor variable.</li>
  <li>This is a <b><i>simple linear regression</b></i> because both variables (the environmental health index and overall EPI ) are quantitative (it is not clear which variable is the response).</li>
  <li>This is a <b><i>2-way ANOVA</b></i> because the response variable (liver weight) is quantitative and the explanatory variables (species [House or Deer Mouse] and where it was located [wild or captive]) is categorical.</li>
</ol>

----
