---
title: "Exercise Key"
subtitle: "Logistic Regression"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3.5
    fig_width: 3.5
    self_contained: false
---

```{r echo=FALSE, eval=FALSE, warning=FALSE}
## Renders an appropriate HTML file and moves to CE directory
source("modules/aaa_ExcKeys/aaa_rmd/zzz_modHTML_CEKeys.R")
modHTML_CEKeys("KEY_Logistic_FlyingFox")
```


----

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
  <li>You should keep as many decimals as possible for &alpha;, &beta;, and intermediate calculations because seemingly "minor" differences in round get compiled when back-transformation, which is common as you saw in logistic regression. So, don't round until your final answer.
  <li>Log(odds) are predicted by plugging a value of "X" (body mass in this case) into the equation of the line, where estimates of &alpha; and &beta; come from table 1 or table 2.</li>
  <li>Odds are predicted by back-transforming the predicted log(odds); i.e., raise the log(odds) to the power of e.</li>
  <li>The predicted probability is computed from the predicted odds with $\frac{\text{odds}}{1+\text{odds}}$.</li>
  <li>When interpreting the slope make sure you realize that it is telling you how the log(odds) (not the odds and not the probability) change with increasing "X" and that that increase is additive.</li>
  <li>When interpreting the back-transformed slope (i.e., e<sup>slope</sup>) make you realize that it is tell you how much the odds (not the log(odds) and not the probability) change with increasing "X" and that the increase is multiplicative</li>
  <li>Questions 7 and 9 are related to moving 100 slopes or 100 back-transformed slopes. On the original scale it is 100 slopes ADDED together and on the back-transformed scale is 100 slopes MULTPLIED together.</li>
  <li>Questions 8 and 10 should pick two values of "X" that are 100 units apart. In question 8, we subtracted because this is on the original scale and we are trying to prove that the slope is an ADDITIVE quantity. In question 10, we divided because this is on the back-transformed scale and we are trying to prove that the back-transformed slope is a MULTIPLICATIVE quantity.</li>
  <li>Questions 11-13 are applications of the formula $\frac{\text{log}\left(\frac{\text{p}}{1-\text{p}}\right)-\alpha}{\beta}$, where p is the given probability of interest and &alpha; and &beta; come from tables 1 and 2 (as in previous questions).
</ul>
</div>

----

## Maturation of Flying Foxes

1. There is a significant **linear** relationship between the log(odds) that a male Flying Fox is mature and its body mass because the p-value for the slope in Table 2 (0.000000342) is less than &alpha;. This implies that there is a significant, though not linear, relationship between the probability that a male Flying Fox is mature and its body mass.

1. The log(odds) that a 454 g male Flying Fox is mature is -13.4568+0.0384*454 = 3.9768.

1. The odds that a 454 g male Flying Fox is mature is e<sup>-13.4568+0.0384*454</sup> = e<sup>3.9768</sup> = 53.3461. This means that a 454 g male Flying Fox is 53 times more likely to be mature than immature.

1. The probability that a 454 g male Flying Fox is mature is $\frac{e^{-13.4568+0.0384*454}}{1+e^{-13.4568+0.0384*454}}$ = 0.9816. This means that approximately 98% of 454 g male Flying Foxes will be mature.

1. The slope tells me that the log(odds) that a male Flying Fox is mature increases by 0.0384 for every 1 g increase in body mass. This value is positive because the probability, odds, and log(odds) of being mature all increase with increasing body mass and adding a positive number means that the log(odds) are increasing.

1. The back-transformed slope (e<sup>0.0384</sup>=1.0391) tells me that the odds that a male Flying Fox is mature increases 1.0391 TIMES for every 1 g increase in body mass. This value is greater than 1 because the probability and odds of being mature all increase with increasing body mass and multiplying by a value greater than 1 means that the odds are increasing.

1. The log(odds) of being mature would increase by 3.84 (i.e., 100 slopes added together, or 100*0.0384) if the body mass increased by 100 g. For clarity, note that the log(odds) this increase would occur by adding 3.84.

1. The log(odds) of being mature for a 354 g male Flying Fox is -13.4568+0.0384*354 = 0.1368. Subtracting this prediction from the predicted log odds for a 454 g male Flying Fox (from above; i.e., 3.9768) gives 3.9768-0.1368 = 3.8400, which is the same value as our previous answer.

1. The odds of being mature would increase by a multiple of 46.53 (i.e., 100 back-transformed slopes multiplied together, or 1.0391<sup>100</sup>).

1. The odds of being mature for a 354 g male Flying Fox is e<sup>0.1368</sup> = 1.1466. Dividing the predicted odds for a 454 g male Flying Fox (from above; i.e., 53.3461) by the predicted odds for a 354 g male Flying Fox gives $\frac{53.3461}{1.1466}$ = 46.53, which is the same value as our previous answer.

1. The body mass where 50% of male Flying Fox are mature is $\frac{\text{log}\left(\frac{0.5}{1-0.5}\right)-(-13.4568)}{0.0384}$ = 350.4 g.

1. The body mass where 10% of male Flying Fox are mature is $\frac{\text{log}\left(\frac{0.1}{1-0.9}\right)-(-13.4568)}{0.0384}$ = 293.2 g.

1. The body mass where 10% of male Flying Fox are immature (which will be calculated by finding where 90% are mature) is $\frac{\text{log}\left(\frac{0.9}{1-0.1}\right)-(-13.4568)}{0.0384}$ = 407.7 g.

----
