---
title: "Exercise Key"
subtitle: "Indicator Variable Regression"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3.5
    fig_width: 3.5
    self_contained: false
---

```{r echo=FALSE, eval=FALSE, warning=FALSE}
## Renders an appropriate HTML file and moves to CE directory
source("modules/aaa_ExcKeys/aaa_rmd/zzz_modHTML_CEKeys.R")
modHTML_CEKeys("KEY_IVR_Trawls")
```
```{r echo=FALSE, include=FALSE, message=FALSE, warning=FALSE}
library(NCStats)
```

----

## Deep-Sea Trawling

<ol start="1">
  <li>The indicator variable is named "SCAV" where SCAV=1 if the species is a "scavenger" and SCAV=0 if the species is a "non-scavenger" (the reference group).</li>
</ol>

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
  <li>The indicator variable is named after the non-reference group. The reference group is alphabetically first in R. Thus, in this case the reference groups is "non-scavengers" and the indicator variable is named after "scavengers."</li>
</ul>
</div>

<ol start="2">
  <li>The ultimate full model is &mu;<sub>LOG.MASS</sub> = &alpha; + &beta;DEPTH + &delta;<sub>1</sub>SCAV + &gamma;<sub>1</sub>SCAV&times;DEPTH.</li>
</ol>

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
  <li>The variables are entered into the ultimate full model in this order -- covariate (i.e., depth), indicator variable (i.e., SCAV), and the interaction variable.</li>
</ul>
</div>

<ol start="3">
  <li>The submodels for both groups are below</li>
  <ul>
    <li>non-scavenger: &mu;<sub>LOG.MASS</sub> = &alpha; + &beta;DEPTH
    <li>scavenger: &mu;<sub>LOG.MASS</sub> = (&alpha;+&delta;<sub>1</sub>) + (&beta;+&gamma;<sub>1</sub>)DEPTH</li></li>
  </ul>
</ol>

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
  <li>The submodel for the "non-scavengers" group is found by plugging in 0 for SCAV in the full model and then simplifying. Essentially everything in the ultimate full model multiplied by SCAV is dropped.</li>
  <li>The submodel for the "scavengers" group is found by plugging in 1 for SCAV in the full model and then simplifying. Essentially the word SCAV is dropped and then the two constants (&alpha; and &delta;<sub>1</sub>) are lumped together and the two items multiplied by the covariate (&beta; and &gamma;<sub>1</sub>) are lumped together.</li>
</ul>
</div>

<ol start="4">
  <li>Interpretations of the coefficients are below.</li>
  <ul>
    <li>&alpha; is the intercept of non-scavenger (reference) group</li>
    <li>&beta; is the slope of non-scavenger (reference) group</li>
    <li>&delta;<sub>1</sub> is the difference in intercept of scavenger and non-scavenger groups (i.e., scavenger-nonscavenger)</li>
    <li>&gamma;<sub>1</sub> is the difference in slopes of scavenger and non-scavenger groups (i.e., scavenger-nonscavenger)</li>
  </ul>
</ol>

<ol start="5">
  <li>The models for the "parallel lines test" are below.</li>
  <ul>
    <li>H<sub>0</sub>: &mu;<sub>LOG.MASS</sub> = &alpha; + &beta;DEPTH + &delta;<sub>1</sub>SCAV</li>
    <li>H<sub>A</sub>: &mu;<sub>LOG.MASS</sub> = &alpha; + &beta;DEPTH + &delta;<sub>1</sub>SCAV + &gamma;<sub>1</sub>SCAV&times;TIME</li>
  </ul>
</ol>

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
  <li>The models in a "parallel lines" test differ only in whether the &gamma;<sub>1</sub> parameter or the interaction variable exists as this is the parameter/variable that indicates if the slopes differ (non-parallel) or not (parallel). Thus, the H<sub>A</sub> is always the ultimate full model and the H<sub>0</sub> is always the ultimate full model without the interaction variables.</li>
</ul>
</div>

<ol start="6">
  <li>The models for the "intercepts test" (assuming parallel lines) are below.</li>
  <ul>
    <li>H<sub>0</sub>: &mu;<sub>LOG.MASS</sub> = &alpha; + &beta;DEPTH</li>
    <li>H<sub>A</sub>: &mu;<sub>LOG.MASS</sub> = &alpha; + &beta;DEPTH + &delta;<sub>1</sub>SCAV</li>
  </ul>
</ol>

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
  <li>The "equal intercepts" or "coincident lines" test is only tested assuming that the lines are parallel; thus, neither model will contain the &gamma;<sub>1</sub> parameter or the interaction variable (as &gamma;<sub>1</sub>=0 for parallel lines). Thus, the models in the "coincident lines" test differ only in whether the models contain the &delta;<sub>1</sub> parameter or the indicator variable.</li>
</ul>
</div>


<ol start="7">
  <li>The data for the scavengers appears curved, which violates the assumption of linearity.</li>
</ol>

----
