---
title: "Two-Way ANOVA Summary"
description: |
  Putting together a complete Two-Way ANOVA analysis.
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    css: "../../css/distill_readings.css"
---

```{r setup, include=FALSE}
library(NCStats)
library(dplyr)
library(ggplot2)
knitr::opts_chunk$set(message=FALSE,comment="#R>  ",
                      fig.align='center',fig.width=3.5,fig.height=3.5)
options(show.signif.stars=FALSE,knitr.kable.NA = '')
clrs <- c("#1dabe6","#1c366a","#c3ced0","#e43034","#fc4e51","#af060f")
```

Specific parts of a full Two-Way ANOVA analysis were described in [the last module](ANOVA2Analysis.html). In this module, a workflow for a full analysis is offered and that workflow is demonstrated with several examples.

# Suggested Workflow
The following is a process for fitting a Two-Way ANOVA model. Consider this process as you learn to fit Two-Way ANOVA models, but don't consider this to be a concrete process for all models.

1. Perform a thorough EDA of the quantitative response variable. Pay special attention to the distributional shape, center, dispersion, and outliers within each treatment/group.
1. Address the independence assumption.
    * If this assumption is not met then other analysis methods must be used.
1. Fit the untransformed ultimate full model (i.e., both main effects and the interaction effect) model with `lm()`.
1. Check the other three assumptions for the untransformed model with `assumptionCheck()`.
    * Check equality of variances with a Levene's test and residual plot.
    * Check normality of residuals with a Anderson-Darling test and histogram of residuals.
    * Check for outliers with an outlier test, residual plot, and histogram of residuals.
1. If an assumption or assumptions are violated, then attempt to find a transformation where the assumptions are met.
    * Use the trial-and-error method with `assumptionCheck()`, theory, or experience to identify a possible transformation. Always try the log transformation first.
    * If only an outlier exists (i.e., there are equal variances and normal residuals) and no transformation corrects the outlier then consider removing the outlier from the data set.
    * Fit the ultimate full model with the transformed response or reduced data set.
1. Construct an ANOVA table for the full model with `anova()`.
    * If a significant interaction exists then do NOT interpret the main effects!!
    * If a significant interaction does NOT exist then interpret the main effects.
        * Fit a new model without the insignificant interaction term.
1. If an effect exists, then use a multiple comparison technique with `emmeans()` and `summary()` to identify specific differences. Describe specific differences using confidence intervals.
    * If a significant interaction exists then perform multiple comparisons on the interaction term using the model that contained an interaction term.
    * If a significant interaction does not exist then perform multiple comparisons for each factor for which a main effect exists using the model without an interaction term.
1. Create a summary graphic of treatment means (i.e., an interaction plot) **on the original scale** with 95% confidence intervals using `ggplot()` and results from `emmeans()` using the model with an interaction term.
1. Write an overall conclusion of your findings.

&nbsp;

# Bacteria (No Transformation)


&nbsp;

# Blood Pressure (No Transformation)


&nbsp;

# Crayfish Foraging (Transformation)


# Corrections {.appendix}
If you see any errors (code, typographical, or logical) please bring these to [my attention](mailto:dogle@northland.edu).

# Reuse {.appendix}
Text and figures are licensed under Creative Commons Attribution [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). Items reused from other places are noted as such.
