---
title: "Exercise Key"
subtitle: "IVR Analysis"
author: Derek H. Ogle
layout: page
css: "/css/modules.css"
output:
  html_document:
    fig_height: 3.5
    fig_width: 3.5
    self_contained: false
---

```{r echo=FALSE, eval=FALSE, warning=FALSE}
## Renders an appropriate HTML file and moves to CE directory
source("modules/ce/aaaKeys/zzz_modHTML_CEKeys.R")
modHTML_CEKeys("KEY_IVRAnalysis_CE1")
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
library(NCStats)
library(emmeans)
source("../../../rhelpers/knitr_setup.R")
```

----

<div class="alert alert-warning">
<strong>Note:</strong> 
<ul>
  <li>Use complete sentences to answer questions.</li>
</ul>
</div>

----

# Bat Morphology
```{r BatData, echo=FALSE, results="hide", fig.show="hide"}
bat <- read.csv("https://raw.githubusercontent.com/droglenc/NCData/master/Batmorph2.csv") %>%
  filter(diet!="vampire") %>%
  mutate(logbodywt=log(bodywt),logmob=log(mob))

ivr1 <- lm(mob~bodywt+diet+bodywt:diet,data=bat)
assumptionCheck(ivr1)
assumptionCheck(ivr1,lambday=0,lambdax=0)
ivr1t <- lm(logmob~logbodywt+diet+logbodywt:diet,data=bat)
anova(ivr1t)
mc1 <- emtrends(ivr1t,specs=pairwise~diet,var="logbodywt",tran="log")
mc1s <- summary(mc1,infer=TRUE,type="response")
```

```{r echo=FALSE}
ad.p <- kPvalue(adTest(ivr1$residuals)$p.value,latex=FALSE)
out.p <- kPvalue(outlierTest(ivr1)$bonf.p,latex=FALSE)
ad.pt <- kPvalue(adTest(ivr1t$residuals)$p.value,latex=FALSE)
out.pt <- kPvalue(outlierTest(ivr1t)$bonf.p,latex=FALSE)
aov.t <- anova(ivr1t)
aov.t.p <- kPvalue(aov.t$"Pr(>F)"[3],latex=FALSE)
mc.t.ag <- kPvalue(mc1s$contrasts$p.value[1],latex=FALSE)
mc.t.ap <- kPvalue(mc1s$contrasts$p.value[2],latex=FALSE)
mc.t.gp <- kPvalue(mc1s$contrasts$p.value[3],latex=FALSE)
mc.t.ag.lci <- formatC(mc1s$contrasts$lower.CL[1],format="f",digits=3)
mc.t.ag.lci <- formatC(mc1s$contrasts$upper.CL[1],format="f",digits=3)
mc.t.ap.uci <- formatC(mc1s$contrasts$lower.CL[2],format="f",digits=3)
mc.t.ap.uci <- formatC(mc1s$contrasts$upper.CL[2],format="f",digits=3)
```

#### R Code and Results
```{r prompt=FALSE, fig.width=7}
<<BatData>>
```
```{r prompt=FALSE, fig.width=4.5}
ggplot(data=bat,mapping=aes(x=logbodywt,y=logmob,
                            color=diet,fill=diet)) +
  geom_point() +
  labs(x="log Body Weight",y="log Main Olfactory Bulb Volume") +  
  theme_NCStats() +  
  geom_smooth(method="lm",se=TRUE,alpha=0.2)
```
